openapi: 3.0.3

info:
  title: Book Pricing API
  version: 1.0.0
  description: API to calculate optimal price for a basket of books using Greedy / DP strategies

paths:
  /api/pricing/v1/calculatePricing:
    post:
      summary: Calculate optimal basket price
      operationId: calculatePricing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookPricingRequest'
      responses:
        '200':
          description: Successful pricing calculation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookPricingResponse'
        '400':
          description: Invalid request

components:
  schemas:

    Book:
      type: string
      enum:
        - CLEAN_CODE
        - CLEAN_CODER
        - CLEAN_ARCHITECTURE
        - TDD_BY_EXAMPLE
        - LEGACY_CODE

    BookPricingRequest:
      type: object
      required:
        - items
      properties:
        items:
          type: object
          additionalProperties:
            type: integer
            minimum: 1

    BookPricingResponse:
      type: object
      required:
        - basketSummary
        - pricing
        - groupBreakdown
      properties:
        basketSummary:
          $ref: '#/components/schemas/BasketSummary'

        pricing:
          $ref: '#/components/schemas/Pricing'

        groupBreakdown:
          type: array
          items:
            $ref: '#/components/schemas/GroupPricing'

    BasketSummary:
      type: object
      required:
        - totalItems
        - uniqueBooks
      properties:
        totalItems:
          type: integer
        uniqueBooks:
          type: integer

    Pricing:
      type: object
      required:
        - basePrice
        - discountAmount
        - finalPrice
      properties:
        basePrice:
          type: number
          format: double
        discountAmount:
          type: number
          format: double
        finalPrice:
          type: number
          format: double

    GroupPricing:
      type: object
      required:
        - groupSize
        - count
        - basePrice
        - discount
        - finalPrice
      properties:
        groupSize:
          type: integer
        count:
          type: integer
        basePrice:
          type: number
          format: double
        discount:
          type: number
          format: double
        finalPrice:
          type: number
          format: double